# Generated by Django 5.1.2 on 2024-11-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_accountcreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountCreation',
        ),
    ]
