# Generated by Django 5.1.2 on 2024-11-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_accountcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_raised',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='campaign_purpose',
            field=models.CharField(choices=[('Child Education', 'child education'), ('Child Healthare', 'child healthcare')], default='Child Education', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
