# Generated by Django 5.1.2 on 2024-11-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
