# Generated by Django 5.1.2 on 2024-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_alter_donation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='donated_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
