# Generated by Django 5.1.2 on 2024-11-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0003_rename_created_at_donation_donated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='campaigns/profile_picture/'),
        ),
    ]
