# Generated by Django 5.1.2 on 2024-11-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0004_alter_campaign_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='campaigns/profile_pictures/'),
        ),
    ]
