# Generated by Django 5.1.2 on 2024-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0005_alter_campaign_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/proofs/'),
        ),
    ]
