# Generated by Django 5.1.2 on 2024-11-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0006_remove_campaign_profile_picture_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/proofs/'),
        ),
    ]
