# Generated by Django 5.1.2 on 2024-11-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0007_alter_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_purpose',
            field=models.CharField(choices=[('Child Education', 'child education'), ('Child Healthare', 'child healthcare')], default='Child Education', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goals',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='uploads/proofs/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='phone_number',
            field=models.CharField(default='+1-6574-323-233', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
