# Generated by Django 5.1.2 on 2024-11-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0010_donation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
