# Generated by Django 5.1.2 on 2024-11-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0011_alter_donation_donated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
