# Generated by Django 5.1.2 on 2024-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0013_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction_ref_num',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
