# Generated by Django 5.1.2 on 2024-11-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0014_withdrawal_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
